ALTER TABLE public.anamneses
  ADD COLUMN IF NOT EXISTS data timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS queixa_principal text,
  ADD COLUMN IF NOT EXISTS historia_atual text,
  ADD COLUMN IF NOT EXISTS historia_familiar text,
  ADD COLUMN IF NOT EXISTS historia_medica text,
  ADD COLUMN IF NOT EXISTS alergias text,
  ADD COLUMN IF NOT EXISTS medicamentos text,
  ADD COLUMN IF NOT EXISTS habitos_vicios_positivos text,
  ADD COLUMN IF NOT EXISTS habitos_vicios_negativos text,
  ADD COLUMN IF NOT EXISTS exame_extra_bucal text,
  ADD COLUMN IF NOT EXISTS exame_intra_bucal text,
  ADD COLUMN IF NOT EXISTS observacoes text,
  ADD COLUMN IF NOT EXISTS anexos jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS assinatura_paciente jsonb,
  ADD COLUMN IF NOT EXISTS assinatura_doutor jsonb,
  ADD COLUMN IF NOT EXISTS token_assinatura text,
  ADD COLUMN IF NOT EXISTS status_assinatura text DEFAULT 'pendente',
  ADD COLUMN IF NOT EXISTS data_expiracao_link timestamp with time zone;