// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxgzjcdaarpgvuonrids.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Z3pqY2RhYXJwZ3Z1b25yaWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzQ1MTEsImV4cCI6MjA2NjExMDUxMX0.yhX-5DKm85pE0ricrv0d3mwygbtrX34fTXlva2Hi4TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);